services:

  postgres:
    image: postgres:18
    container_name: postgres-sec-cont
    restart: always
    environment:
      POSTGRES_DB: healthcoredb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  spring-app:
    build: .
    container_name: healthcore-api
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/healthcoredb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data: